"""Windows helper to stage Linux boot from NTFS.

This script is designed to be frozen with PyInstaller into an exe. It
focuses on the setup tasks that can be performed from an administrative
PowerShell or Command Prompt on Windows 10:

* Download a Linux ISO into a working directory on an NTFS partition.
* Generate a minimal ``menu.lst`` for grub4dos to loop-boot that ISO.
* Generate a ``.bat`` script that wires a grub4dos boot entry into BCD.

The script does not attempt to install a bootloader automatically.
Instead it produces the files and commands required so you can review
and run them with elevated privileges.
"""
from __future__ import annotations

import argparse
import hashlib
import sys
import textwrap
import urllib.request
from pathlib import Path

DEFAULT_ISO_URL = (
    "https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd/debian-12.5.0-amd64-DVD-1.iso"
)
DEFAULT_ISO_NAME = "linux.iso"
DEFAULT_WORKDIR = Path.home() / "linux-install-helper"

MENU_TEMPLATE = """# Auto-generated by install_helper.py
# Copy this file to the root of the NTFS partition that hosts your ISO.
# Ensure grldr and grldr.mbr from grub4dos are also present in the same partition.

color blue/green yellow/black white/blue white/black

# Loop-boot the downloaded ISO. Adjust kernel parameters as needed.
title Boot Linux installer from ISO
find --set-root /{iso_name}
map /{iso_name} (hd32)
map --hook
chainloader (hd32)
boot
"""

BCD_BATCH_TEMPLATE = """@echo off
REM Auto-generated by install_helper.py
REM Run this from an elevated Command Prompt.

set WORKPART=%SystemDrive%
if NOT "%~1"=="" set WORKPART=%~1

bcdedit /create /d "Linux via grub4dos" /application BOOTSECTOR > tmp_guid.txt
for /f "tokens=1,2" %%a in (tmp_guid.txt) do if "%%a"=="The" set GUID=%%b
if "%GUID%"=="" for /f "tokens=2" %%a in (tmp_guid.txt) do set GUID=%%a

echo Created entry: %GUID%

bcdedit /set %GUID% device partition=%WORKPART%
bcdedit /set %GUID% path \grldr.mbr
bcdedit /displayorder %GUID% /addlast
bcdedit /timeout 5

del tmp_guid.txt

echo Done. Ensure grldr.mbr and menu.lst exist at %WORKPART%\
"""

